version: "3.7"
services:

  dbms:
    image: mysql:8.0.20
    environment:
      - TZ=${OS_TIMEZONE}
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping --silent"]
    ports:
      - ${DB_PORT}:3306
